SELECT Title FROM Movies WHERE Id = 6
SELECT Title FROM Movies WHERE year BETWEEN 2000 AND 2010
SELECT Title FROM Movies WHERE year NOT BETWEEN 2000 AND 2010
SELECT Title, year FROM Movies WHERE Id <= 5
